# Generated by Django 2.0.5 on 2018-06-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=30)),
                ('hage', models.IntegerField()),
                ('hgender', models.BooleanField()),
                ('hdesc', models.CharField(max_length=200)),
                ('hbook', models.ForeignKey(on_delete=True, to='myhero.BookInfo')),
            ],
        ),
    ]
