# Generated by Django 2.0.5 on 2018-06-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhero', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hbook',
            field=models.ForeignKey(null=True, on_delete=True, to='myhero.BookInfo'),
        ),
    ]
