# Generated by Django 2.0.5 on 2019-01-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhero', '0003_auto_20180620_0710'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hage',
            field=models.IntegerField(null=True),
        ),
    ]
