# Generated by Django 2.0.5 on 2019-01-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhero', '0004_auto_20190128_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hgender',
            field=models.BooleanField(default=0),
        ),
    ]
